### ISSUE TITLE
SpeedBump Logic 

### ISSUE THREAD

**Issue by NicolaBernini** [element-fi/elf-contracts#208]
Hi, 

here 

https://github.com/element-fi/elf-contracts/blob/main/contracts/Tranche.sol#L298

You are allowing anybody to set the speedbump once if specific conditions are met, and then it has to be reset to zero before it can be set again 

Where does this reset happen?

**Comment by pvienhage** [comment]
Hi, the speedbump cannot be reset to zero, since if it could funds in a negative interest rate outcome could be locked indefinitely. 
The purposes of the speedbump are (1) mitigate or at least give a warning withdraw period in cases where a flashloan or economic manipulation could result in artificial negative interest rates and (2) give time for mitigation if a real negative interest rate indecent occurs. Neither is substantially improved by a reset process because withdraw only happens once and is monotonically decreasing overtime.
